export const vehicles = [
    {
        id: "VEH001",
        make: "Toyota",
        model: "Corolla",
        licensePlate: "ABC123",
        status: "Active",
        fuelEfficiency: 28.5,
    },
    {
        id: "VEH002",
        make: "Honda",
        model: "Civic",
        licensePlate: "DEF456",
        status: "Active",
        fuelEfficiency: 30.2,
    },
    {
        id: "VEH003",
        make: "Ford",
        model: "F-150",
        licensePlate: "GHI789",
        status: "Maintenance Required",
        fuelEfficiency: 22.1,
    },
    {
        id: "VEH004",
        make: "Chevrolet",
        model: "Silverado",
        licensePlate: "JKL012",
        status: "Active",
        fuelEfficiency: 24.8,
    },
    {
        id: "VEH005",
        make: "Nissan",
        model: "Rogue",
        licensePlate: "MNO345",
        status: "Active",
        fuelEfficiency: 27.3,
    },
    {
        id: "VEH006",
        make: "Hyundai",
        model: "Sonata",
        licensePlate: "PQR678",
        status: "Maintenance Required",
        fuelEfficiency: 28.9,
    },
    {
        id: "VEH001",
        make: "Toyota",
        model: "Corolla",
        licensePlate: "ABC123",
        status: "Active",
        fuelEfficiency: 28.5,
    },
    {
        id: "VEH002",
        make: "Honda",
        model: "Civic",
        licensePlate: "DEF456",
        status: "Active",
        fuelEfficiency: 30.2,
    },
    {
        id: "VEH003",
        make: "Ford",
        model: "F-150",
        licensePlate: "GHI789",
        status: "Maintenance Required",
        fuelEfficiency: 22.1,
    },
    {
        id: "VEH004",
        make: "Chevrolet",
        model: "Silverado",
        licensePlate: "JKL012",
        status: "Active",
        fuelEfficiency: 24.8,
    },
    {
        id: "VEH005",
        make: "Nissan",
        model: "Rogue",
        licensePlate: "MNO345",
        status: "Active",
        fuelEfficiency: 27.3,
    },
    {
        id: "VEH006",
        make: "Hyundai",
        model: "Sonata",
        licensePlate: "PQR678",
        status: "Maintenance Required",
        fuelEfficiency: 28.9,
    },
];
